### ISSUE TITLE
Date display not correctly (Update)

### ISSUE THREAD

**Issue by Qisheng-Tang** [computationalmystic/augur-group25#2]
**Is your feature request related to a problem? If so, please describe the problem:**
Two statistic graph in our software do not show correct end date.

**To Reproduce**
1. Go to ' ec2-18-217-244-45.us-east-2.compute.amazonaws.com:3333'
2. Click on 'github.com/twitter/twemoji'
3. Click on 'Experimental'
4. Scroll down to 'Line changed/Month' and 'Commits/week'
5.  The End date shows Dec 31, 1969 (See bug)

**Expected Behavior**
The end date should be when the repository update recently.

**Screenshots**
![屏幕快照 2019-04-28 下午6 23 48](https://user-images.githubusercontent.com/39931310/56871412-2e7dcd80-69e3-11e9-9155-1a0a7d48f7ca.jpg)
![屏幕快照 2019-04-28 下午6 23 56](https://user-images.githubusercontent.com/39931310/56871417-46555180-69e3-11e9-9740-d5b30bb9ee69.jpg)

**Desktop (please complete the following information):**
-OS: Mac OS 10.14.4
-Browser: Safari

**Describe the solution you'd like:**
We hope to fix this bug so that the date can be shown in a regular year

**Solution**
We will try to modify our code to solve this problem. We will try to modify 'DynamicLineChart.vue'

**Comment by Qisheng-Tang** [comment]
This issue may be the most difficult one. We will figure out other issues first.

**Comment by Arianardo** [comment]
We just fixed this on lines changed per week and month graphs so now they display the correct end date.  Still working on commits per week graph as it is now blank after these changes.

**Comment by Arianardo** [comment]
Commits per week is up but not displaying correctly.

**Comment by Arianardo** [comment]
All graphs are up and display the date correctly.

**Comment by ghost** [comment]
In order to fix the issue we needed to add a function to reformat the date variable so that it can be accepted by Vega Lite. This is the solution we came up with:
<img width="757" alt="Screen Shot 2019-05-04 at 7 47 54 PM" src="https://user-images.githubusercontent.com/47017176/57187079-65eeed00-6eaf-11e9-8487-282cb728ceee.png">

**Comment by ghost** [comment]
This issue was assigned too and worked on by all three group members. Gabe sat down with us and walked us through how this function should we implemented, and then we all worked together to get it to work.

**Comment by ghost** [comment]
This is how the new date is formatted in the API Endpoint for "commits per week". The other endpoints now format their data very similar to this.
<img width="1440" alt="Screen Shot 2019-05-05 at 3 21 33 PM" src="https://user-images.githubusercontent.com/47017176/57199863-d0546b80-6f49-11e9-9c34-0e12cb3eaf93.png">
