### ISSUE TITLE
Add graph navigator (Update)

### ISSUE THREAD

**Issue by Qisheng-Tang** [computationalmystic/augur-group25#4]
**Is your feature request related to a problem? If so, please describe the problem:**
Sometimes, users may feel confused as they do not know what is the meaning of different data

**Describe the solution you'd like:**
Add a graph navigator to make it easier to understand the graph and values

**Describe alternatives you've considered:**
Add a line of below the graph to show what is the meaning of x-axis and y-axis

**Additional context:**

**Comment by ghost** [comment]
This issue falls under the scope of the "sub-graph" issue so we decided to remove this issue. The sub-graph issue will cover what we meant when we say "graph navigator."
