### ISSUE TITLE
Make the graph color fit the webpage

### ISSUE THREAD

**Issue by Qisheng-Tang** [computationalmystic/augur-group25#5]
**Is your feature request related to a problem? If so, please describe the problem:**
The graph variables' color is not fit into the webpage

**Describe the solution you'd like:**
Tweak the graph variables to make it fit in with the color scheme

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Qisheng-Tang** [comment]
Today we have tried some possible ways for this issue. We will continue try to solve some technical problem in office hour

**Comment by ghost** [comment]
For this issue we would just like to change the Vega Lite graph specs so that the graph is similar to font/color/style to the other graphs on Augur. We would do this by passing an array of colors and then implementing these in the graph's javascript functions.

**Comment by ghost** [comment]
This issue has been assigned to Qisheng Tang. We will work together to make sure the graphs fit the scheme of the other graphs.

**Comment by Qisheng-Tang** [comment]
I will try to change the color of line first. I will use Vega-lite online editor to make a test.

**Comment by ghost** [comment]
We have decide to push this issue to sprint 4 because we felt that implementing the graphs correctly was a more important issue to deal with. We will definitely work on this issue further and hopefully complete it during the 4th sprint.

**Comment by Qisheng-Tang** [comment]
I have tried in Vega-lite for graph color. We will test whether it will work
<img width="188" alt="屏幕快照 2019-05-11 下午8 15 50" src="https://user-images.githubusercontent.com/39931310/57576628-c7700800-7429-11e9-9931-7e40ed495915.png">

**Comment by ghost** [comment]
We have changed the color of the graph by committing changes to the facadeLineChart.vue file. This has changed the line color from blue (default option) to black. 

<img width="185" alt="Screen Shot 2019-05-16 at 11 33 48 AM" src="https://user-images.githubusercontent.com/47017176/57871235-7d42aa00-77ce-11e9-961e-69195c205feb.png">
