### ISSUE TITLE
Update "Commits per Week" SQL

### ISSUE THREAD

**Issue by mRockey23** [computationalmystic/augur-group25#8]
**Describe the bug:**
The SQL does not retrieve the date of commit in the correct format so the Vega Lite graphs will have trouble displaying it.

**To Reproduce:**
1. Go to ec2-18-217-244-45.us-east-2.compute.amazonaws.com:3333
2. Click on the 'experimental' card
3. Scroll down to 'Commits/Week'
4. See the graph not displaying the data correctly.

**Expected behavior:**
You should notice that the graph displays 1961 as the date and no lines being shown on the graph. This is due to the date not being formatted correctly so no information will show up.

**Screenshots**
<img width="938" alt="Screen Shot 2019-05-03 at 3 23 25 PM" src="https://user-images.githubusercontent.com/47017176/57163665-6d32cf80-6db7-11e9-8649-607ec7d87d5b.png">

**Desktop (please complete the following information):**
 - OS: macOS v10.14.1
 - Browser: Chrome

**Additional context**
We worked on this issue in office hours. We need to concatenate the date so that Vega Lite accepts it.

**Comment by ghost** [comment]
For this issue we noticed that the "commits per week" SQL was given incorrect parameters, and that the SQL was not returning a "date" variable. This would prevent the graph from displaying the data with the correct timeframe and break it. Our solution was to change the SQL so it selected "author_date" and returned that so it could be used by our graphs.
<img width="649" alt="Screen Shot 2019-05-03 at 3 08 21 PM" src="https://user-images.githubusercontent.com/47017176/57187270-7acc8000-6eb1-11e9-9c45-9ea8ebef8e0f.png">

**Comment by ghost** [comment]
This issue is complete so we closed the issue.

**Comment by ghost** [comment]
Now, author_date is selected from the facade database. This is how the endpoints displays the new data:
<img width="1440" alt="Screen Shot 2019-05-05 at 3 21 33 PM" src="https://user-images.githubusercontent.com/47017176/57199894-1f9a9c00-6f4a-11e9-84e4-8c64ff748049.png">
