### ISSUE TITLE
Change the style of title (End user Test)

### ISSUE THREAD

**Issue by Qisheng-Tang** [computationalmystic/augur-group25#9]
**Is your feature request related to a problem? If so, please describe the problem:**
This is an End User Test. I asked my friends to test our software. The main problem is the color of our lines looks bad. Another problem is the type of words need to be modified.
![屏幕快照 2019-05-05 下午7 26 03](https://user-images.githubusercontent.com/39931310/57202606-b4ae8c80-6f6c-11e9-866a-4c4a7b2957d9.jpg)

**Describe the solution you'd like:**
We will try to modify the .vue file. I will test in Vega-lite first.

**Additional text**

This issue may be combined with " Make the color fit the webpage". As it is a End User test, I record here as an issue.

**Comment by ghost** [comment]
For this issue we will try to implement it in the next sprint. This can be easily changed by edit the specs() function of the Vega Lite graphs and just messing around with some of the configurations. We will assign this issue to Qisheng.

**Comment by Qisheng-Tang** [comment]
I have solved it in Vega-lite. Wait for test in out system: 
<img width="279" alt="屏幕快照 2019-05-11 下午8 15 36" src="https://user-images.githubusercontent.com/39931310/57576631-f0909880-7429-11e9-837f-0de393679d50.png">

**Comment by ghost** [comment]
We were able to implement the change by inserting this code into facadeLineChart.vue:

<img width="435" alt="Screen Shot 2019-05-16 at 11 34 21 AM" src="https://user-images.githubusercontent.com/47017176/57871534-24bfdc80-77cf-11e9-815c-97ab9ad72851.png">

**Comment by ghost** [comment]
This changed the font from bold to regular to fit the rest of the Augur website: 

<img width="239" alt="Screen Shot 2019-05-16 at 11 39 21 AM" src="https://user-images.githubusercontent.com/47017176/57871600-4325d800-77cf-11e9-82d3-84dc1418f85c.png">
